language: node_js
node_js:
    - "6.10.2"
install:
    - npm install
script:
    - npm test
cache: 
  - npm install
env: 
  - NODE_ENV=test
before_script:
  - createdb more-recipe --username=postgres
  - sequelize db:migrate 
after_success:
  - npm run coveralls