language: node_js
services:
  - postgresql
node_js:
    - "6.10.2"
install:
    - npm install
script:
    - npm test
cache: 
  - npm install
before_script:
  - psql -c 'create database more-recipes;' -U postgres
  - sequelize db:migrate --env development
after_success:
  - npm run coveralls