language: node_js
node_js:
    - "6.10.2"
install:
    - npm install
script:
    - npm test
cache: 
  - npm install
before_script:
  - createdb more-recipes --username=postgres
  sequelize db:migrate --env development
after_success:
  - npm run coveralls